version: "3.3"
#services:
#  web:
#    image: web:latest
#    build: .
#    ports:
#      - "80:80"
#    command: python3 manage.py runserver 0.0.0.0:80
#    volumes:
#      - .:/code
services:
  web:
    image: web:latest
    build: .
    container_name: django-deployment
    ports:
      - '8005:80'
      - '3501:3500'
      - '4701:81'
    volumes:
      - $PWD/www:/var/www/html